### ISSUE TITLE
row.getHeight() and sheet.getColumnWidth(xxx)

### ISSUE THREAD

**Issue by dutrieux** [pjfanning/excel-streaming-reader#101]
Could you please implements these methods :

row.getHeight() and sheet.getColumnWidth(xxx)

It's will be a nice feature.

Duto

**Comment by dutrieux** [comment]
I have an other request for sheet.getPaneInformation() to have the configuration of pane (split or freeze).

Thanks for your work !

**Comment by pjfanning** [comment]
v3.6.1 is released
