### ISSUE TITLE
StreamingSheet cannot be re-iterated

### ISSUE THREAD

**Issue by daniel-shuy** [pjfanning/excel-streaming-reader#106]
@pjfanning thanks for forking and maintaining [monitorjbl/excel-streaming-reader](https://github.com/monitorjbl/excel-streaming-reader).

This issue is from the original [monitorjbl/excel-streaming-reader](https://github.com/monitorjbl/excel-streaming-reader) (monitorjbl/excel-streaming-reader#97).

Essentially, the `StreamingSheet` breaks the concept of an `Iterable` - `Iterator`s are not meant to be reusable, hence `Iterable#iterator()` should provide a new "fresh" `Iterator` on each call.

`StreamingSheet#iterator()` creates a new `StreamingRowIterator` on each call, but `StreamingRowIterator` uses the `StreamingSheetReader`'s row cache:
https://github.com/pjfanning/excel-streaming-reader/blob/0c3bb7cbb47f4b2240bc449e9021d6b6c58d6f3d/src/main/java/com/github/pjfanning/xlsx/impl/StreamingSheet.java#L42-L45
https://github.com/pjfanning/excel-streaming-reader/blob/0c3bb7cbb47f4b2240bc449e9021d6b6c58d6f3d/src/main/java/com/github/pjfanning/xlsx/impl/StreamingSheetReader.java#L730-L740
https://github.com/pjfanning/excel-streaming-reader/blob/0c3bb7cbb47f4b2240bc449e9021d6b6c58d6f3d/src/main/java/com/github/pjfanning/xlsx/impl/StreamingSheetReader.java#L827-L858

At the moment the only way to get a fresh `Iterator` (eg. to iterate through a `Sheet` more than once) is to reload the entire `Workbook`, which is really inefficient.

I'm wondering if this can be reworked/restructured by moving the `StreamingSheetReader` to `StreamingRowIterator`.

This would probably require moving the `XMLEventReader` and `StreamingSheetReader` initialization to `StreamingRowIterator`:
https://github.com/pjfanning/excel-streaming-reader/blob/0c3bb7cbb47f4b2240bc449e9021d6b6c58d6f3d/src/main/java/com/github/pjfanning/xlsx/impl/StreamingWorkbookReader.java#L220-L228

Would you be open to a PR for this?

**Comment by pjfanning** [comment]
I know about the issue but am not anxious to do a large refactor like this. The general point of streaming is that you read the streamed data once. It is inefficient to read it twice.

For those cases, where you do need to read the data twice, creating a 2nd StreamingWorkbookReader is not that complicated.

If more users come along with the same requirement I might reconsider - but I do have more interesting things to do with my life.

**Comment by pjfanning** [comment]
If you would like to submit a PR yourself I will review it.

**Comment by daniel-shuy** [comment]
> For those cases, where you do need to read the data twice, creating a 2nd StreamingWorkbookReader is not that complicated.

Yes, normally its not difficult to change it to create a new `Workbook`, but when migrating from `poi-ooxml` to `excel-streaming-reader`, ideally there should be as little changes as possible, especially if it is used extensively.

> If you would like to submit a PR yourself I will review it.

Thanks! Since I have a project that extensively uses `poi-ooxml` with comprehensive tests (which I'm trying to migrate to `excel-streaming-reader`), I can use it to test the changes.

**Comment by pjfanning** [comment]
@daniel-shuy the solution to this issue might also fix https://github.com/pjfanning/excel-streaming-reader/issues/92

Ideally any PR for this issue would
* not change the API for users you currently use excel-streaming-reader and who are happy with its existing iterator behaviour
* not cause a performance degradation for users who want to iterate the sheets and rows once

**Comment by daniel-shuy** [comment]
@pjfanning thanks! I rebased my branch onto main, should've looked at the `4.0-prep` branch first though, looks like you've already done some of the stuff I did, would've saved me some time 😅

Should I target the `main` or `4.0-prep` branch?

**Comment by daniel-shuy** [comment]
@pjfanning thanks for merging the PR and for continuing to improve the library. Do you have any estimate on when you plan to release `4.0.0`? (No pressure by the way, I understand quality code takes time)

**Comment by pjfanning** [comment]
I haven't yet decided on when to do a release. 4.0.0-SNAPSHOT is published after every successful build - to https://oss.sonatype.org/content/repositories/snapshots

I may do a 4.0.0M1 release later in the week. I want to discourage existing users from upgrading due to the large number of internal changes and the need to do performance testing.

**Comment by daniel-shuy** [comment]
@pjfanning Thanks! I'll use `4.0.0-20220327.180204-22` to test for now, will let you know if I encounter any issues

**Comment by pjfanning** [comment]
4.0.0-RC1 is released
