### ISSUE TITLE
row.getRowStyle()

### ISSUE THREAD

**Issue by dutrieux** [pjfanning/excel-streaming-reader#114]
Could you please implements this method :

row.getRowStyle()

It's will be a nice feature.

Duto

**Comment by pjfanning** [comment]
Wanna try it yourself? It's not really my intention to support every possible xlsx option.

I can review any PRs that come in.

**Comment by pjfanning** [comment]
I haven't tested this - but the rudiments of what is needed is in https://github.com/pjfanning/excel-streaming-reader/tree/row-style - I guess the main thing I need is an xlsx that has row styles set

**Comment by dutrieux** [comment]
I do a PR

**Comment by pjfanning** [comment]
4.0.0-RC1 is released
