### ISSUE TITLE
Saving Workbook as Non-Strict OOXML file

### ISSUE THREAD

**Issue by ElRakiti** [pjfanning/excel-streaming-reader#132]
Hi,

I'm using this lib to open a Strict OOXML Excel Workbook. However, I actually need to process the Excel file with a different library which we are using already (it's even more complicated as we are basically using a low-code platform). Long-story short, I cannot further process the file with your library, I want to use it for reading the strict ooxml file and store it as a "normal" xlsx file (with a different name?) so I can import the usual way.

Right now, I'm at the point where I can read the file:

`File xlsxFile = new File(filename);
        if (!xlsxFile.exists()) {
            System.err.println("Not found or not a file: " + xlsxFile.getPath());
            return;
        }

        try (Workbook workbook = StreamingReader.builder()
                .rowCacheSize(100)
                .bufferSize(4096)
                .setSharedStringsImplementationType(SharedStringsImplementationType.TEMP_FILE_BACKED)
                .open(xlsxFile)) {
            for (Sheet sheet : workbook) {
                System.out.println("Sheet: " + sheet.getSheetName());     
            }
        }`

I have two questions:

1. How can I store the file (optional: with a different filename) as a normal, non-strict XLSX file?
2. Is there a way to first check if the file is actually a strict ooxml file? Asking because we get different Excel files for further processing, some are strict ooxml, some not.

Thank you very much!

**Comment by pjfanning** [comment]
1. This project is for reading files. There is no plan to support writing files.
2. org.apache.poi.openxml4j.opc.OPCPackage.isStrictOoxmlFormat() -- this was added for the POI 5.1.0 release.

**Comment by ElRakiti** [comment]
Thanks for the quick reply!

1. That's a bummer...I first found your repo https://github.com/pjfanning/ooxml-strict-converter, but since it is archived and this repo was suggested, I came here :). I will try to figure out how to save the file.
2. Got it, thanks!
