### ISSUE TITLE
Migrating from monitorjbl 2.1.0 to pjfanning latest version, backward compatibility 

### ISSUE THREAD

**Issue by satyamcs12** [pjfanning/excel-streaming-reader#152]
I was migrating code from monitorjbl 2.1.0 to latest version of pjfanning.
After deploying change saw below exceptions for some of file reads
 Exception while reading file 
 java.lang.IllegalStateException: This cell has a shared formula and it seems setReadSharedFormulas has been set to false or the formula can't be evaluated

I didnot see this exception with monitorjbl 2.1.0 ,  so is pjfanning latest version not backward compatible with monitorjbl 2.1.0?

**Comment by pjfanning** [comment]
https://github.com/pjfanning/excel-streaming-reader/issues/151 and the new v4.0.4 release may be of interest.

**Comment by satyam-meesho** [comment]
Thanks @pjfanning 
setReadSharedFormulas(true) fixed the issue.
Just one question on same lines, any specific reason to have default value for readSharedFormulas as false, because had it been true it would have been backward compatible and not required any code change on version upgrade.

**Comment by satyamcs12** [comment]
Thanks @pjfanning 
setReadSharedFormulas(true) fixed the issue.
Just one question on same lines, any specific reason to have default value for readSharedFormulas as false, because had it been true it would have been backward compatible and not required any code change on version upgrade.

**Comment by pjfanning** [comment]
Applying shared formulas is fairly new behaviour and as you can see with #151, there are still issues popping up.
