### ISSUE TITLE
Decoding unicode characters without rich text formatting

### ISSUE THREAD

**Issue by ggsurrel** [pjfanning/excel-streaming-reader#166]
I have an application handling very large excel files. I am using the `TEMP_FILE_BACKED` shared Strings implementation.
I would like to avoid using the `setFullFormatRichText` option, as I do not need any format details and as I see a non-negligible performance drop when using it.

Everything is working great, except I sometimes get some encoded unicode characters, mostly `_x000D_`.

Is there any way to get the text decoded without the overhead of the rich text format option ?

**Comment by pjfanning** [comment]
Can't you post-process the strings yourself? If you want to write a solution and have it added to poi-shared-strings, I'll have a look at it. I'm going to close this issue as the code you are talking about is not even part of this lib.
