### ISSUE TITLE
New version of the reader.

### ISSUE THREAD

**Issue by ewoutreinders** [pjfanning/excel-streaming-reader#178]
Hello, 

Our NexusIQ noticed a vulnerability by reference of an apache library, commons-text. However, i also noticed it is al ready updated in the repository. It is about the commons-text library, which is referenced trough poi-shared-strings, from version 1.9.0 to 1.10.0.

Is it possible to create a new version containing the latest libraries?

Sincerely,

Ewout

**Comment by pjfanning** [comment]
You can control which commons-text jar you use using your own build scripts. I do not do releases just to minor bumps in dependency jars.

**Comment by pjfanning** [comment]
To be clear, this lib does not use any of the string substitution logic in commons-text - so this lib is not affected by issues in that code.

**Comment by pjfanning** [comment]
https://search.maven.org/artifact/com.github.pjfanning/excel-streaming-reader/4.0.5/jar which was released last year has commons-io 2.11.0 dependency.
