### ISSUE TITLE
Formula evaluation

### ISSUE THREAD

**Issue by mike-podolskiy90** [pjfanning/excel-streaming-reader#191]
I have the following block of code (regular POI):
```
...
FormulaEvaluator formulaEvaluator = new XSSFFormulaEvaluator((XSSFWorkbook) book);
...
Row row = iter.next();
for (int i = 0; i < rowSize; i++) {
  Cell c = row.getCell(i, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK);
  formulaEvaluator.evaluate(c);
  val[i] = dataFormatter.formatCellValue(c, formulaEvaluator);
}
```
How can I do something like that with this library please? How should I correctly evaluate the formula?
Thank you!

**Comment by pjfanning** [comment]
Formula evaluation is not a priority for me. The xlsx file already has cached values for each formula cell.

This library gives you those values.

Why not trust Excel has the right values cached in the xlsx file?

I am one of the main Apache POI contributors and I know just how far from perfect the POI Formula Evaluator is.

**Comment by mike-podolskiy90** [comment]
Thanks for the quick reply!
I've just started exploring the library. I've removed formula evaluator, but still have it like this:
```
val[i] = dataFormatter.formatCellValue(c)
```
This works fine, but for formula cells returns formula itself, not the actual value. How can I adjust it please?

**Comment by pjfanning** [comment]
have a read of the DataFormatter javdocs - there is an option to help

**Comment by pjfanning** [comment]
https://javadoc.io/doc/org.apache.poi/poi/latest/org/apache/poi/ss/usermodel/DataFormatter.html#setUseCachedValuesForFormulaCells(boolean)

**Comment by mike-podolskiy90** [comment]
Great! That's what I need. I just didn't have `setReadSharedFormulas(true)`, but after setting it and configuring `setUseCachedValuesForFormulaCells ` it works just fine.
Thanks a lot, very much appreciated.
