### ISSUE TITLE
how to find out that a numeric value is empty

### ISSUE THREAD

**Issue by hgfrey** [pjfanning/excel-streaming-reader#220]
I have empty numeric cells. How do I find out the cell is empty? In this case, getNumericCellValue returns 0.0, but that is not what is in the Excel document.

How can I find out that the cell is empty.

**Comment by pjfanning** [comment]
You must understand that getNumericCellValue must return a double, the API as defined cannot return null. The Cell interface has lots of getters. You could try getStringCellValue which returns an empty string for blank cells.

https://www.javadoc.io/static/com.github.pjfanning/excel-streaming-reader/4.2.1/com/github/pjfanning/xlsx/impl/StreamingCell.html

You could try using POI's DataFormatter which returns the cell values in a format meant to closely match how the values appear in Excel. You can this used in https://github.com/pjfanning/excel-streaming-reader-sample/blob/main/src/main/java/com/github/pjfanning/poi/sample/StreamingRead.java
