### ISSUE TITLE
Set rowcacheSize(100) error！

### ISSUE THREAD

**Issue by yimengfan** [pjfanning/excel-streaming-reader#239]
The excel size ：9M 
Set rowCacheSize(100) error, set to 10 will success!
![image](https://github.com/pjfanning/excel-streaming-reader/assets/26621257/3019804e-e2ab-4ca0-8697-584a79089539)

**Comment by pjfanning** [comment]
I don't know what this issue is about. Can you provide a reproducible test case?

**Comment by pjfanning** [comment]
closing due to lack of anything to investigate
