### ISSUE TITLE
Read large xlsx file with blank/empty cells

### ISSUE THREAD

**Issue by gokhyildiz** [pjfanning/excel-streaming-reader#40]
There is aim to read large excel files with this library. But some cells of excel files are empty. When I use the algorithm defined in the project, it does not read these blank cells (because it was written with an iterator). How can i fix this problem? Rows need to be read with blank cells. Otherwise, there is an inconsistency in the excel file to be read. Thanks.

**Comment by pjfanning** [comment]
if the iterator skips (empty) rows, you have the row number of each row so you can have your code check the row number as you go along and handle the missing empty rows in your code

likewise, for cells

**Comment by gokhyildiz** [comment]
I found the problem. Previously I was checking as cell.equals(null) and I could not find empty cells. Then i changed the content and it got better. Thanks.

![alg](https://user-images.githubusercontent.com/32950356/118325377-0b5fe100-b50c-11eb-99a2-1046db081ef6.png)

![xlsx](https://user-images.githubusercontent.com/32950356/118325199-ca67cc80-b50b-11eb-8de5-85e720369b16.png)

![out](https://user-images.githubusercontent.com/32950356/118325198-c9369f80-b50b-11eb-9b35-70aaa0126031.png)
