### ISSUE TITLE
Support for cached formula results in StreamingCell.getBooleanCellValue

### ISSUE THREAD

**Issue by slawo-ch** [pjfanning/excel-streaming-reader#44]
When reading a cell value that is a formula with boolean type I'm currently getting a NotSupportedException originating from  com.github.pjfanning.xlsx.impl.StreamingCell.getBooleanCellValue(StreamingCell.java:219) 

Sample file:
[boolean_formula.xlsx](https://github.com/pjfanning/excel-streaming-reader/files/6604039/boolean_formula.xlsx)

Cached formula results are read successfully from cells of other types. 
Is there some inherent problem with making it work for booleans?

Happy to take a stab at it if you're open to PRs.

Best Wishes
Slawo

**Comment by pjfanning** [comment]
@slawo-ch I'm happy to merge a fix if you can provide one

**Comment by pjfanning** [comment]
For formula cells, you could modify getBooleanCellValue to call getCachedFormulaResultType

**Comment by slawo-ch** [comment]
Yes - was thinking to go that route. PR coming through some time tomorrow :)

**Comment by pjfanning** [comment]
v3.0.5 is released
