### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.poi.util.XMLHelper.newXMLReader()Lorg/xml/sax/XMLReader;

### ISSUE THREAD

**Issue by danmaidesenling** [pjfanning/excel-streaming-reader#48]
Hi
     I met this issue : java.lang.NoSuchMethodError: org.apache.poi.util.XMLHelper.newXMLReader()Lorg/xml/sax/XMLReader
     coudl you fix this ?

**Comment by pjfanning** [comment]
this is caused by you using a version of POI that is too old

**Comment by danmaidesenling** [comment]
thank you, updated to poi 5.0
