### ISSUE TITLE
ZipPackage takes a lot of memory

### ISSUE THREAD

**Issue by danmaidesenling** [pjfanning/excel-streaming-reader#49]
![zippackage](https://user-images.githubusercontent.com/7588416/123608363-45254680-d831-11eb-91ef-125dbb94d236.png)
As you can see in the picture. 
xlsx file 97M, 1,000,000 rows. 25 columns
this is my code :
`StreamingReader.builder()
                    .rowCacheSize(50)
                    .bufferSize(1024)
                    .open(file);`

how can i avoid this or will optimize this in the next release ?
thanks in advance for your response.

**Comment by pjfanning** [comment]
this code is in POI - there are no plans to remove the POI code that excel-streaming-reader - that is 42k which most people would not regard as much memory.

If you don't like POI, I would recommend https://github.com/dhatim/fastexcel - which has no POI dependencies as far as I know.

**Comment by pjfanning** [comment]
The latest release of POI (also needs up to date version of excel-streaming-reader) has some settings that can reduce the memory footprint by using temp files - see https://github.com/pjfanning/excel-streaming-reader#reading-very-large-excel-files
