### ISSUE TITLE
workbook.getSheetAt(0).getWorkbook() returns null

### ISSUE THREAD

**Issue by spyro2000** [pjfanning/excel-streaming-reader#87]
Hello,

loving your library :)

But when I got a sheet reference from a workbook and then try to get the workbook back, I got NULL as result.

`workbook.getSheetAt(0).getWorkbook() // null`

I would expect, that I'll just get a reference to the "workbook" I used for my `.getSheetAt(0)` call?

That makes it impossible for me, to close the workbook after I processed the sheet later in my code (I do not have a direct reference to the workbook there, only for the sheet)

**Comment by pjfanning** [comment]
it is implemented in most recent versions - maybe you are using an old version?

**Comment by spyro2000** [comment]
Hello @pjfanning,

thanks for your anwer. I am using this versions:

````
    implementation("org.apache.poi:poi:5.1.0")
    implementation("org.apache.poi:poi-ooxml:5.1.0")
    implementation("com.github.pjfanning:excel-streaming-reader:3.2.4")
````

**Comment by pjfanning** [comment]
I think this new commit fixes it - https://github.com/pjfanning/excel-streaming-reader/commit/d99dcf02108e97bf474e10943776892faa971050 

I'm not planning to release this for a few days - because I already did a new release last night.

I don't think it should be hard to workaround this issue in the mean time.

**Comment by spyro2000** [comment]
It is, I just passed around the original workbook reference and everything worked fine. Thank you :)

**Comment by pjfanning** [comment]
v3.2.6 is released
