### ISSUE TITLE
Invalid Automatic-Module-Name

### ISSUE THREAD

**Issue by michael-spahn** [pjfanning/excel-streaming-reader#97]
v3.4.1 cannot be referenced in a module-info.java file because the Automatic-Module-Name 'com.github.pjfanning.excel-streaming-reader' is not valid (I think dashes are not allowed).

**Comment by pjfanning** [comment]
Thanks for the report - I've released https://github.com/pjfanning/excel-streaming-reader/releases/tag/v3.4.2 just now.

I tested it with this branch in the sample: https://github.com/pjfanning/excel-streaming-reader-sample/tree/module-info
